name: Install KiBOT with Caching

on:
  workflow_dispatch:

jobs:
  install-kiauto:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up repository and cache APT packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-${{ hashFiles('kicad-setup.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Add KiCad PPA and Install KiCad
      run: |
        echo "kicad" > kicad-setup.txt
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt update
        sudo apt install --install-recommends kicad

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('kibot-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install KiBot
      run: |
        pip3 install kibot

    - name: Verify Installation
      run: |
        kibot --version
        kicad --version